# Generated by Django 5.1.1 on 2024-09-12 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Kategiriya',
                'verbose_name_plural': 'Kategorilar',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Taglar',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Kontent')),
                ('image', models.ImageField(upload_to='news/images/', verbose_name='Rasm')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rilishlar")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faollik')),
                ('is_banner', models.BooleanField(default=False, verbose_name='Bannerga joylash')),
                ('is_weekly', models.BooleanField(default=False, verbose_name='Haftalik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsers.category', verbose_name='Kategoriya')),
                ('tags', models.ManyToManyField(to='newsers.tag', verbose_name='Taglar')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
    ]
