# Generated by Django 5.1.1 on 2024-09-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True, verbose_name='Slug'),
        ),
    ]
