# Generated by Django 5.1.1 on 2024-09-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsers', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='shares',
            field=models.PositiveIntegerField(default=0, verbose_name='Ulashishlar'),
        ),
    ]
